spring.application.name=mabibli

# Connexion PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SUPABASE_DB_URL}

# Hibernate + Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

#OpenLibrary
open-library.base-url=https://openlibrary.org
open-library.user-agent=${OPEN_LIBRARY_USER_AGENT:MaBibliotheque/1.0}