create table users (
                       id bigint generated by default as identity primary key,
                       username varchar(50) not null unique,
                       password varchar(255) not null,
                       created_at date not null,
                       updated_at date
);

create table libraries (
                           id bigint generated by default as identity primary key,
                           title varchar(100) not null,
                           user_id bigint not null,
                           created_at date not null,
                           updated_at date,

                           constraint fk_library_user
                               foreign key (user_id)
                                   references users(id)
                                   on delete cascade,

                           constraint uk_library_user_title
                               unique (user_id, title)
);

create table series (
                        id bigint generated by default as identity primary key,
                        title varchar(255) not null,
                        user_id bigint not null,
                        created_at date not null,
                        updated_at date,

                        constraint fk_series_user
                            foreign key (user_id)
                                references users(id)
                                on delete cascade,

                        constraint uk_series_user_title
                            unique (user_id, title)
);

create table books (
                       id bigint generated by default as identity primary key,
                       isbn varchar(25),
                       open_library_id varchar(50) not null,
                       title varchar(255) not null,
                       author varchar(255) not null,
                       status varchar(30) not null,
                       reading_date date,
                       description text,
                       cover varchar(500),
                       pages integer,
                       series_id bigint,
                       series_index integer,
                       library_id bigint not null,
                       created_at date not null,
                       updated_at date,

                       constraint fk_book_library
                           foreign key (library_id)
                               references libraries(id)
                               on delete cascade,

                       constraint fk_book_series
                           foreign key (series_id)
                               references series(id)
                               on delete set null,

                       constraint uk_book_library_open_library
                           unique (library_id, open_library_id),

                       constraint ck_book_pages_positive
                           check (pages is null or pages > 0),

                       constraint ck_book_series_index_positive
                           check (series_index is null or series_index > 0)
);

create table book_category (
                               book_id bigint not null,
                               category varchar(50) not null,

                               primary key (book_id, category),

                               constraint fk_book_category_book
                                   foreign key (book_id)
                                       references books(id)
                                       on delete cascade
);

create index idx_library_user on libraries(user_id);
create index idx_book_library on books(library_id);
create index idx_series_user on series(user_id);